limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
# create a "zone" so all workers have a shared 10 MB token limit, 
# with a refill rate of 5 requests per addr key.
server {
    listen 80;
    server_name localhost;
    resolver 127.0.0.11 valid=30s; # resolve the address via Docker's internal DNS network
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        }
    location /api {
        limit_req zone=api_limit burst=10 nodelay;
        # burst is used to provide a temporary limit buffer. With "nodelay", the buffer is available immediately
        # Without the delay, requests over the limit but below the buffer would have been put in a queue
        limit_req_status 429;
        set $upstream_backend http://backend:5000; # set a variable to wait till a request acually comes
        proxy_pass $upstream_backend;
        proxy_set_header Host $host; # give the backend the actual URL typed
        proxy_set_header X-Real-IP $remote_addr; # give the backend the real IP of request-maker
    }
}