services:
  # The frontend service (React + Nginx)
  frontend:
    container_name: note-app-frontend
    image: note-app-frontend
    build:
      context: .  # Path to the folder containing the Dockerfile
      dockerfile: frontend/dockerfile # The actual filename (optional if named 'Dockerfile')
      args:
        - VITE_IS_DOCKER=true
    ports:
      - "8080:80"
    depends_on:
      - backend

  # The backend service (Flask)
  backend:
    stop_signal: SIGINT
    stop_grace_period: 10s
    container_name: note-app-backend
    image: note-app-backend
    build:
      context: .
      dockerfile: backend/dockerfile
    env_file:
      - ./backend/.env
    volumes:
      # Format: [Host Path on Windows] : [Path inside Container]
      # Mirror the database paths so docker can persist changes to disk and load changed data from disk
      - ./backend/data:/flask_app/backend/data
    depends_on: # wait for database container to complete
      db_setup:
        condition: service_completed_successfully
    # Nginx talks to it internally on port 5000, no need to map to localhost
    expose:
      - "5000"

  db_setup: # ensure database is setup before running servers
    container_name: database-builder
    image: note-app-backend
    command: python -m backend.database.database_init
    volumes:
      - ./backend/data:/flask_app/backend/data
    env_file:
      - ./backend/.env